
import Main from '../components/Main.jsx'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About.jsx'
import Skills from '../components/Skills.jsx'
import Projets from '../components/Projets.jsx'
import Cv from '../components/Cv.jsx'
import Contact from '../components/Contact.jsx'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Tristan Blasin / Front-End Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projets />
      <Cv />
      <Contact />
    </div>
  )
}
